name: Test

on: [push, pull_request]

jobs:
  test:
    name: Test all packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm test
